name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # or any version you support

      # 3. Install build tools
      - run: python -m pip install --upgrade build twine

      # 4. Build sdist and wheel
      - run: python -m build

      # 5. Publish to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
